### ISSUE TITLE
Feature Ideas

### ISSUE THREAD

**Issue by yutyo** [KelvinShadewing/supertux-advance#1]
Hi,

First of all, this game is very nice and has amazing potential as a SuperTux sequel, which is aged. I am sure many people had this in mind and you initiated this as you know the libre game world closely.  Great channel btw.

I think the game can have the following features:

### More Player Capabilities
Even in current state, Tux seems to have many capabilities like jumping between walls and sliding. I would love to see spinning and fly-running effects in SMB3/SMBW, and all sorts of bending effects in SMB2 combined.

### Rideables
Like Yoshi, SuperTux Advance can have rideable characters that have FOSS theme such as [GNU](https://en.wikipedia.org/wiki/Wildebeest). GNU can eat enemies and put them in "forks" and "commits" towards enemies like Yoshi puts them in eggs and throws them in SMBW2. Also some obscure stuff like [Oracle Tux Mech Suit](https://lignux.com/wp-content/uploads/2013/12/Oracle_Tux.png) can be added as rare rideables to the game.

### Different Powerups
Super Mario games after SMB have powerups not limited to mushroom and flower. Cape is one of them and it can be added like in this [GNU/Linux mascot art](https://en.wikifur.com/w/images/thumb/6/69/GNU-Linux.png/200px-GNU-Linux.png). 

### Mode 7 and FX-like effects
The game would look retro yet advanced if it includes effects similar to what is used in Super Mario World 2: Yoshi's Island, which looks both retro and modern.

### Minibosses
The game definitely need to have more bosses than Nolok and Yeti, and need to have references to proprietary software mascots who serve to Nolok in his evil plans against GNU world. A mystery man with redhat (referring to the company that screws Linux) can be a chaotic normal character appearing after a miniboss is defeated, just like Protoman in Mega Man 3. A plot twist to the game can be added where Tux discovers Nolok is a virus in service of a grand boss named I-Bee-aM, an evil queen bee in a hive full of proprietary software and viruses.

### Minigames
The game can have minigames like in SMB3 and SMBW, like memory and slot games.

That's what I can say for now, as the game is in early development. I appreciate the effort and will contribute to the project in my free time.

**Comment by KelvinShadewing** [comment]
Sorry it took so long to see this. I just completely missed the notification.

What do you mean by bending effects from SMB2? Do you mean the transition used when going into a warp zone? I'm not sure about spin jumping, since I don't want Tux to be too much like Mario; that's why he can slide anywhere to deal with enemies that can't be jumped on.

I had considered making Konqi a rideable character, but decided I'd rather have him be fully playable. He'll be unlocked upon completing the first castle. I don't have plans to bring rideable characters back right now, but maybe vehicles could be done. As for Gnu putting enemies in "forks" and "commits", I have no idea how that would be represented visually.

For Mode-7 and Super FX, I'm still learning. I'd love to come up with something that uses those, but for right now, that's just impossible. If I do do it, though, it'll probably be for something like Extreme Tux Racer.

I'm not gonna put references to proprietary software in this. I'm not trying to make some statement with this game; it's just for fun. Bosses will be whatever feels appropriate for the worlds they show up in.

Mini games would really be fun, and something I have thought about, since I'm making this to learn with.
