### ISSUE TITLE
Tiling issues within Fish Mines

### ISSUE THREAD

**Issue by tulip-sudo** [KelvinShadewing/supertux-advance#99]
![image](https://user-images.githubusercontent.com/63363329/171727445-feaca528-b729-4f0c-91a3-50c5dff17ee5.png)

**Comment by KelvinShadewing** [comment]
This happens when tilesets are extended horizontally. I think @Frostwithasideofsalt edited that one recently. Tilesets should be extended vertically when adding new tiles to keep this from happening. The fix for this would be to open the map in Tiled and say yes when it asks to redo the tile references. I'll fix this in the unstable branch for now.

**Comment by tulip-sudo** [comment]
Forgot to close this lmao
